[package]
name        = "polysim-core"
version.workspace    = true
edition.workspace    = true
license.workspace    = true
authors.workspace    = true
repository.workspace = true

[dependencies]
bigsmiles-core = { workspace = true }
thiserror      = { workspace = true }
